import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserRouter,Link,Route,Routes,useParams} from 'react-router-dom';
import './styles.css';

const API=import.meta.env.VITE_API_URL||'http://localhost:8000';
async function get(path:string){const r=await fetch(API+path);if(!r.ok)throw new Error(await r.text());return r.json();}
function Shell({children}:{children:React.ReactNode}){return <div className="shell"><aside><h1>WeatherSentinel</h1><p className="muted">SIH26073</p><nav><Link to="/">Dashboard</Link><Link to="/stations">Stations</Link><Link to="/live">Live Monitoring</Link><Link to="/evaluation">Evaluation</Link><Link to="/models">Models</Link></nav></aside><main>{children}</main></div>}
function Stat({label,value}:{label:string,value:React.ReactNode}){return <div className="card"><span className="muted">{label}</span><strong>{value}</strong></div>}
function Dashboard(){const [data,setData]=useState<any>(null);const [err,setErr]=useState('');useEffect(()=>{get('/api/v1/stations').then(setData).catch(e=>setErr(e.message))},[]);const stations=data?.stations||[];const active=stations.reduce((n:any,s:any)=>n+(s.active_anomalies?.length||0),0);const healthy=stations.filter((s:any)=>s.health?.state==='HEALTHY').length;return <Shell><h2>System Dashboard</h2>{err&&<div className="error">{err}</div>}<div className="grid"><Stat label="Stations" value={stations.length}/><Stat label="Healthy" value={healthy}/><Stat label="Active anomalies" value={active}/><Stat label="Backend" value="Connected"/></div><section className="panel"><h3>Station overview</h3>{stations.length===0?<p className="muted">Register stations or process observations through the API.</p>:<table><thead><tr><th>Station</th><th>Observations</th><th>Health</th><th>Latest</th></tr></thead><tbody>{stations.map((s:any)=><tr key={s.station.station_id}><td><Link to={'/stations/'+s.station.station_id}>{s.station.station_id}</Link></td><td>{s.observations}</td><td><span className="badge">{s.health?.state||'UNKNOWN'}</span></td><td>{s.latest_observation?.timestamp||'—'}</td></tr>)}</tbody></table>}</section></Shell>}
function Stations(){const [data,setData]=useState<any>({stations:[]});useEffect(()=>{get('/api/v1/stations').then(setData)},[]);return <Shell><h2>Stations</h2><div className="panel"><table><thead><tr><th>ID</th><th>Name</th><th>Health</th><th>Score</th><th>Anomalies</th></tr></thead><tbody>{data.stations.map((s:any)=><tr key={s.station.station_id}><td><Link to={'/stations/'+s.station.station_id}>{s.station.station_id}</Link></td><td>{s.station.name||'—'}</td><td>{s.health?.state||'UNKNOWN'}</td><td>{s.health?.score?.toFixed?.(1)||'—'}</td><td>{s.active_anomalies?.length||0}</td></tr>)}</tbody></table></div></Shell>}
function Station(){const {stationId}=useParams();const [data,setData]=useState<any>(null);const [an,setAn]=useState<any>(null);useEffect(()=>{Promise.all([get('/api/v1/stations/'+stationId),get('/api/v1/stations/'+stationId+'/anomalies')]).then(([a,b])=>{setData(a);setAn(b)})},[stationId]);if(!data)return <Shell><p>Loading…</p></Shell>;return <Shell><h2>Station {stationId}</h2><div className="grid"><Stat label="Health" value={data.health?.state||'UNKNOWN'}/><Stat label="Score" value={data.health?.score?.toFixed?.(1)||'—'}/><Stat label="Observations" value={data.observations}/><Stat label="Active anomalies" value={data.active_anomalies?.length||0}/></div><section className="panel"><h3>Latest observation</h3><pre>{JSON.stringify(data.latest_observation,null,2)}</pre></section><section className="panel"><h3>Anomaly timeline</h3>{(an?.anomalies||[]).slice().reverse().map((x:any)=><div className="event" key={x.timestamp}><b>{x.anomaly.severity}</b> · {x.diagnosis.primary_root_cause} · {x.timestamp}</div>)}</section></Shell>}
function Live(){const [events,setEvents]=useState<any[]>([]);useEffect(()=>{const ws=new WebSocket((API.startsWith('https')?'wss':'ws')+'://'+API.replace(/^https?:\/\//,'')+'/api/v1/ws/events');ws.onmessage=e=>setEvents(v=>[JSON.parse(e.data),...v].slice(0,50));return()=>ws.close()},[]);return <Shell><h2>Live Monitoring</h2><div className="panel"><p className="muted">Streaming WebSocket events</p>{events.length===0?<p>Waiting for analysis events…</p>:events.map((e,i)=><div className="event" key={i}>{e.type} · {e.station_id||''} · {e.timestamp||''}</div>)}</div></Shell>}
function Evaluation(){const [m,setM]=useState<any>(null);useEffect(()=>{get('/api/v1/evaluation/metrics').then(setM)},[]);return <Shell><h2>Evaluation</h2><div className="grid">{m&&Object.entries(m).filter(([k])=>typeof m[k as keyof typeof m]==='number').map(([k,v])=><Stat key={k} label={k} value={Number(v).toFixed(3)}/>)}</div><section className="panel"><pre>{JSON.stringify(m,null,2)}</pre></section></Shell>}
function Models(){const [m,setM]=useState<any>(null);useEffect(()=>{get('/api/v1/models').then(setM)},[]);return <Shell><h2>Models & System</h2><section className="panel"><pre>{JSON.stringify(m,null,2)}</pre></section></Shell>}
function App(){return <Routes><Route path="/" element={<Dashboard/>}/><Route path="/stations" element={<Stations/>}/><Route path="/stations/:stationId" element={<Station/>}/><Route path="/live" element={<Live/>}/><Route path="/evaluation" element={<Evaluation/>}/><Route path="/models" element={<Models/>}/></Routes>}
createRoot(document.getElementById('root')!).render(<BrowserRouter><App/></BrowserRouter>);
